simple_app/documents/urls.py
from django.urls import path
from . import views

app_name = 'documents'

urlpatterns = [
    path('', views.documents_list, name="list"),
    path('new-document/', views.document_new, name="new-document"),
    path('edit-document/<slug:slug>', views.document_edit, name="edit-document"),
    path('delete-document/<slug:slug>', views.document_delete, name="delete-document"),
    path('<slug:slug>', views.document_page, name="page"),
]

simple_app/simple_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('contact/', views.contact),
    path('about/', views.about),
    path('documents/', include('documents.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

simple_app/documents/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Document(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "documents")
    title = models.CharField(max_length = 75)
    description = models.TextField(blank = True)
    date = models.DateTimeField(auto_now_add = True)
    slug = models.SlugField(blank = True)
    file = models.FileField(blank = True, null = True)

    class Meta:
        unique_together = ("owner", "slug")

    def __str__(self):
        return self.title
        
    

simple_app/users/models.py
from django.db import models

# Create your models here.

simple_app/documents/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'description', 'file']
        labels = {
            'title': 'Document Title',
            'description': 'Short Description',
            'file': 'Upload File'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Enter document title',
                'class': 'input_field'
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Enter a short description',
                'rows': 4,
                'class': 'edit_desc_area'
            }),
            'file': forms.ClearableFileInput(attrs={
                'class': 'edit_file_upload'
            })
        }

simple_app/documents/views.py
from django.shortcuts import render, redirect
from .models import Document
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from .forms import DocumentForm
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
@login_required(login_url='/users/login/')
def documents_list(request):
    query = request.GET.get('q', '')
    documents = Document.objects.filter(owner=request.user).order_by('-date') # - in descending order

    if query:
        documents = documents.filter(
            Q(title__icontains=query) | 
            Q(description__icontains=query)
        )

    paginator = Paginator(documents, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'documents/documents_list.html', { 'documents': page_obj, 'query': query })


@login_required(login_url='/users/login/')
def document_page(request, slug):
    document = get_object_or_404(Document, slug=slug, owner=request.user)
    return render(request, 'documents/document_page.html', { 'document': document })


@login_required(login_url='/users/login/')
def document_new(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        file = request.FILES.get('file')

        if not title or not file:
            return HttpResponse("title and file are required", status=400)

        document = Document.objects.create(
            owner = request.user,
            title = title,
            description = description,
            file = file,
            slug = slugify(title)
        )

        return redirect('documents:list')

    return render(request, 'documents/document_new.html')


@login_required(login_url='/users/login/')
def document_edit(request, slug):
    document = get_object_or_404(Document, slug=slug, owner=request.user)

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES, instance=document)
        if form.is_valid():
            form.save()
            return redirect('documents:page', slug=document.slug)
    else:
        form = DocumentForm(instance=document)

    return render(request, 'documents/document_edit.html', {'form': form, 'document': document})


@login_required(login_url="/users/login/")
def  document_delete(request, slug):
    document = get_object_or_404(Document, slug=slug, owner=request.user)

    if request.method == "POST":
        document.delete()
        return redirect("documents:list")

    return render(request, "documents/document_confirm_delete.html", {"document": document})

simple_app/simple_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

# def homepage(request):
#     return HttpResponse("hello")

# def about(request):
#     return HttpResponse("first django app")

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

simple_app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("documents:list")
    else:
        form = UserCreationForm()

    return render(request, 'users/register.html', { 'form': form })


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("documents:list")
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', { "form": form })


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("documents:list") 

simple_app/documents/templates/documents/document_confirm_delete.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - delete document
{% endblock %}

{% block content %}
    <h1>Are you sure?</h1>

    <p>Do you really want to delete <strong>{{ document.title }}</strong>? </p>

    <form method="post">
        {% csrf_token %}
        <div class="delete_buttons">
            <button class="delete_document">Yes, delete</button>
            <a href="{% url 'documents:page' slug=document.slug %}" class="cancel_button">Cancel</a>
        </div>
    </form>
{% endblock %}

simple_app/documents/templates/documents/document_edit.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - edit document
{% endblock %}

{% block content %}
    <h1> edit document - {{ document.title }}</h1>
    <form class="form" method="post" action="{% url 'documents:edit-document' slug=document.slug %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        {% if document.file %}
        <p>Current file: <a href="{{ document.file.url }}">Download</a></p>
        {% endif %}

        <div class="edit_buttons">
            <button class="submit">Save</button>
            <a href="{% url 'documents:page' slug=document.slug %}" class="cancel_button">Cancel</a>
        </div>
    </form>
{% endblock %}

simple_app/documents/templates/documents/document_new.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - new document
{% endblock %}

{% block content %}
    <h1> new document</h1>
    <form class="form" method="post" action="{% url 'documents:new-document' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title">Title of the document</label><input type="text" name="title" id="title_file" required>
        <label for="description">Description of the document</label><input type="text" name="description" id="description_file">
        <label for="file">Select your file</label><input type="file" name="file" id="file" required>
        <button class="submit">Submit</button>
    </form>
{% endblock %}

simple_app/documents/templates/documents/document_page.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - {{ document.title }}
{% endblock %}

{% block content %}
    <h1>{{ document.title }}</h1>
    <section class="document_lines">
        <p>{{ document.description }}</p>
        <p>{{ document.date}}</p>

        {% if document.file %}
        <a href="{{ document.file.url }}" class="doc_url" target="_blank">pobierz plik</a><br/>

        {% else %}
        <p class="doc_url">no file added</p>

        {% endif %}

        <div class="buttons">
            <a href="{% url 'documents:list' %}" class="cancel_button">Go back</a>
            <a class="edit_document" href="{% url 'documents:edit-document' slug=document.slug %}">Edit</a>
            <a class="delete_document" href="{% url 'documents:delete-document' slug=document.slug %}">Delete</a>
        </div>
    </section>
{% endblock %}

simple_app/documents/templates/documents/documents_list.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - your documents
{% endblock %}

{% block content %}
    <h1>your documents</h1>

    <section class="documents_list">
        <div class="search_div">
            <form action="" method="get" class="search_form">
                <input type="text" placeholder="input title or description" value="{{ query }}" name="q" class="search_input">
                <button type="submit" class="submit_button"> Search </button>
            </form>
        </div>

        {% if documents %}
            {% for document in documents %}
                <article class="document">
                    <a href="{% url 'documents:page' slug=document.slug %}" class="document_link">
                        <h3>
                            {{ document.title }}
                        </h3>
                        <p>{{ document.description }}</p>
                        <p>{{ document.date}}</p>
                    </a>
                </article>
            {% endfor %}

        {% elif not documents and query %}
            <h2>no results for <span class="info_query">{{ query }}</span></h2>
        {% elif not documents %}
            <h2>Your documents list is empty, add some clicking link on your left side</h2>
        {% endif %}

        <div class="pagination">
            {% if documents.has_previous %}
                <a href="?q={{ query }}&page={{ documents.previous_page_number }}" class="arrows">&larr;</a>
            {% endif %}

            <span>
                Strona <b>{{ documents.number }}</b> z <b>{{ documents.paginator.num_pages }}</b>
            </span>

            {% if documents.has_next %}
                <a href="?q={{ query }}&page={{ documents.next_page_number }}" class="arrows">&rarr;</a>
            {% endif %}
        </div>

    </section>

    <p class="end_par">you can go back by clicking this <a href="/">link</a></p>
{% endblock %}

simple_app/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    Doctus – about
{% endblock %}

{% block content %}
    <h1>About Doctus</h1>

        <p>
            <strong>Doctus</strong> is a minimalist document management application
            designed for people who value simplicity, speed, and privacy.
        </p>

        <p>
            The app allows you to create, store, edit, and organize your personal documents
            in one secure place, accessible anytime after logging in.
        </p>

        <p>
            Built with the <strong>Django</strong> framework, Doctus focuses on clean design,
            server-side rendering, and reliable session-based authentication.
        </p>

        <p>
            This project was created as a learning and portfolio application,
            showcasing practical backend development and UI fundamentals.
        </p>

    <p class="end_par">
        Go back to the <a href="/">homepage</a>.
    </p>
{% endblock %}

simple_app/templates/contact.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - contact
{% endblock %}

{% block content %}
    <h1>Welcome to contact page</h1>

        <p>
            <strong>Call me</strong> 123-456-678
            or <strong>text me</strong> email@example.com
        </p>

        <br />
    <p class="end_par">
        Go back to the <a href="/">homepage</a>.
    </p>
{% endblock %}

simple_app/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Doctus
{% endblock %}

{% block content %}
    <h1>Welcome to Doctus</h1>

        <p>
            <strong>Doctus</strong> is a simple and secure Django-based application
            for managing your personal documents.
        </p>

        <p>
            Create, store, and organize your documents with ease —
            all in one place, accessible only to you.
        </p>

        <p>
            Use the navigation menu to explore the app or jump directly to:
        </p>
        <br />
        <p>
            👉 Learn more <a href="/about">about the application</a><br>
            👉 View and manage <a href="/documents">your documents</a>
        </p>
{% endblock %}

simple_app/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Doctus
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a class="name" href="/">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo_icon">
            <span>Doctus</span>
        </a>

        <div class="links">
            <a href="/" aria-label="home" title="Home">Homepage</a> <hr />
            <a href="/about" aria-label="about" title="about">About</a>  <hr />
            
            {% if user.is_authenticated %}

            <a href="{% url 'documents:list' %}" aria-label="documents" title="documents">Your documents</a>  <hr />
            <a href="{% url 'documents:new-document' %}" aria-label="new-documents" title="new-document">New document</a>  <hr />
            <form action="{% url 'users:logout' %}" method="POST">
                {% csrf_token %}
                <button class="logout" title="logout">Logout</button>
            </form>

            {% else %}

            <a href="{% url 'users:login' %}" aria-label="login" title="login">Login</a>  <hr />
            <a href="{% url 'users:register' %}" aria-label="register" title="register">Register</a>

            {% endif %}

            <button id="button_theme" class="button_theme">☀️</button>


        </div>

        <div class="contact">
            <a href="/contact" aria-label="contact" title="contact">Contact</a>  <hr />
            <p class="author_par">App made by Florek &copy; 2026 </p>
        </div>

    </nav>

    <main>
        {% block content %}
            Here is the content
        {% endblock %}
    </main>
</body>
</html>

simple_app/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - login
{% endblock %}

{% block content %}
    <h1>Login into your account</h1>
    <form class="form" action="/users/login/" method="post" >
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button class="submit">Submit</button>
    </form>
{% endblock %}

simple_app/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Doctus - register
{% endblock %}

{% block content %}
    <h1>Register new user</h1>
    <form class="form" action="/users/register/" method="post" >
        {% csrf_token %}
        {{ form }}
        <button class="submit">Submit</button>
    </form>
{% endblock %}